# 需安装Nacos注册中心
# 启动多个provider或consumer，注意修改port
server:
  port: 8072
spring:
  application:
#    name: ms-provider
    name: ms-consumer
  cloud:
    nacos:
      discovery:
        group: SRV_REG_GROUP
        server-addr: dev:8848
# 应用信息
info:
  app:
    name: ${spring.application.name}
    version: "1"
    description: ${spring.application.name}
feign: # 断路器
  hystrix:
    enabled: true
management:
  endpoints: # Actuator监控
    enabled-by-default: true